# Generated by Django 5.2.7 on 2025-12-02 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_role_customuser_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='karma_bad',
            field=models.IntegerField(default=0, verbose_name='Плохая карма'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='karma_good',
            field=models.IntegerField(default=0, verbose_name='Добрая карма'),
        ),
    ]
