# Generated by Django 5.2.7 on 2025-12-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_karma_bad_customuser_karma_good'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_karma_date',
            field=models.DateField(blank=True, null=True, verbose_name='Последняя дата кармы'),
        ),
    ]
