# Generated by Django 5.2.7 on 2025-11-20 00:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='master',
        ),
        migrations.AddField(
            model_name='booking',
            name='massage',
            field=models.TextField(blank=True, help_text='Описание массажа'),
        ),
        migrations.AddField(
            model_name='booking',
            name='master_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, help_text='Список ID мастеров', size=None),
        ),
        migrations.AddField(
            model_name='booking',
            name='payments',
            field=models.JSONField(default=list, help_text='Список оплат: [{amount, method}, ...]'),
        ),
        migrations.AddField(
            model_name='booking',
            name='steam_program',
            field=models.TextField(blank=True, help_text='Программа парения'),
        ),
    ]
