# Generated by Django 5.2.7 on 2025-11-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_remove_booking_client_name_remove_booking_master_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='source',
            field=models.CharField(choices=[('user', 'Мастер'), ('system', 'Бронь')], default='user', max_length=10),
        ),
    ]
