# Generated by Django 5.2.7 on 2025-11-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_booking_hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='hall',
            field=models.CharField(choices=[('muromets', 'Муромец'), ('nikitich', 'Никитич'), ('popovich', 'Попович'), ('massage_l', 'Массаж Л'), ('massage_p', 'Массаж П')], default='muromets', help_text='Зал, где проходит услуга', max_length=20),
        ),
    ]
