"""
Django settings for my_bathhouse_backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
# my_bathhouse_backend/settings.py
import os
from pathlib import Path
from datetime import timedelta

# from django.conf.global_settings import AUTH_USER_MODEL

# Создайте пути внутри проекта следующим образом: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Определяем папку для медиа файлов (если нужно, можно заменить)
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')  # Папка для хранения загрузок

# URL для обслуживания медиа файлов
MEDIA_URL = '/media/'  # URL для обращений к загруженным данным

# Отключаем автоматическое добавление слэша к URL
APPEND_SLASH = True

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bd2td8c*d9pyy3^8$%oko6%ng#=w7_-)x))u2j2kqa&(*@2@-n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['bathhouse-app.ru', 'www.bathhouse-app.ru']
# ALLOWED_HOSTS = ['localhost', '127.0.0.1']
# ['localhost', '127.0.0.1']: Эти два адреса означают, что приложение
#   примет запросы только с локальных машин (например, при разработке).
#   Когда вы развертываете сайт публично, вам потребуется добавить
#   реальные домены, на которых ваше приложение размещено
#   (например, example.com, www.example.com).
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    # 'bathhouse-app.ru',
    # 'www.bathhouse-app.ru',
] # ALLOWED_HOSTS = ["*"] Можно оставить открытым для
# тестирования


# Application definition

INSTALLED_APPS = [
    # 'my_bathhouse_backend.apps.users.apps.UsersConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'my_bathhouse_backend.apps.users',
    'corsheaders',
    #     для работы с PDF
    'my_bathhouse_backend.apps.reports.apps.ReportsConfig',
    'django.contrib.postgres',  # ← обязательно для JSONField
    'django.contrib.humanize',
    #     календарь
    'my_bathhouse_backend.apps.scheduling',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS_ALLOWED_ORIGIN_REGEXES = [
#     r'^http://localhost:3000.*$',
#     # 'http://192.168.1.169:3000',
#     # '*'
# ]

# === ДОВЕРЕННЫЕ ИСТОЧНИКИ ДЛЯ CSRF ===
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://192.168.1.169:3000',
]

# Без CSRF_TRUSTED_ORIGINS Django блокирует POST-запросы с фронтенда,
# даже если CORS разрешён.
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',  # фронтенд на localhost:3000
    "http://127.0.0.1:3000",
    "http://192.168.1.169:3000",
]

# CORS_ALLOWED_ALL_ORIGINS = True

# Опционально: разрешить куки/авторизацию (если нужны)
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

ROOT_URLCONF = 'my_bathhouse_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug', # добавлено 14.10.25
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'my_bathhouse_backend.wsgi.application'

ASGI_APPLICATION = 'my_bathhouse_backend.asgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'bathhouse_db',       # Название базы данных
        'USER': 'bathhouse_user',     # Пользователь PostgreSQL
        'PASSWORD': 'strongpassword', # Пароль пользователя
        'HOST': 'localhost',          # Локальный хост
        'PORT': '5432',               # Стандартный порт
    }
}

# =========================
# Активируйте ведение журнала запросов в Django,
# чтобы видеть подробности SQL-запросов и ошибок:

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.db.backends': {
            'level': 'DEBUG',
            'handlers': ['console'],
            'propagate': True, ##
        },
        '': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}
# =========================

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'users.CustomUser'

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ===================================
# ДЛЯ : INSTALLED_APPS = [
#     # Другие установленные приложения...
#     'rest_framework_simplejwt.token_blacklist',
# ]
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  # Время жизни токена
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),  # Время жизни
    # refresh-токена
}
# ===================================

# Email настройки — Yandex
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'fa.daliastro@gmail.com'  # ← твой новый Gmail
EMAIL_HOST_PASSWORD = 'rphihxdutppmxpxm'  # ← вставь сюда без пробелов!
DEFAULT_FROM_EMAIL = 'fa.daliastro@gmail.com'
# === Получатели отчётов ===
REPORT_RECIPIENTS = [
    'fadeev.music.studio@yandex.ru',
]