# Generated by Django 5.2.7 on 2025-11-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=100, verbose_name='Имя администратора')),
                ('created_at', models.DateTimeField(db_index=True, verbose_name='Дата и время создания')),
                ('data', models.JSONField(help_text='Полная структура строк, оплат, мастеров', verbose_name='Данные отчёта')),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Общая оплата')),
                ('inserted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата сохранения')),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
                'ordering': ['-created_at'],
            },
        ),
    ]
