# Generated by Django 5.2.7 on 2025-11-30 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата отчёта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('data', models.JSONField(help_text='Услуги, клиенты, зарплата', verbose_name='Данные отчёта')),
                ('total_clients', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Всего клиентов')),
                ('total_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая зарплата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_reports', to=settings.AUTH_USER_MODEL, verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Отчёт мастера',
                'verbose_name_plural': 'Отчёты мастеров',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
