# Generated by Django 5.2.7 on 2025-12-01 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_masterreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='masterreport',
            name='paid',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Оплачено'),
        ),
        migrations.AddField(
            model_name='masterreport',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AddField(
            model_name='masterreport',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_reports', to=settings.AUTH_USER_MODEL, verbose_name='Кем оплачено'),
        ),
    ]
