# Generated by Django 5.2.7 on 2025-12-03 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterreport',
            name='partially_paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Частично оплачено'),
        ),
        migrations.AlterField(
            model_name='masterreport',
            name='paid',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Полностью оплачено'),
        ),
    ]
